name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snek-site
          path: |
            index.html
            script.js
            service-worker.js
            game.js
            style.css
            assets
